# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: 'mmistakes/jekyll-theme-basically-basic'
title: La Ruta de la Cebada
description: >- # this means to ignore newlines until "baseurl:"
  Una ruta de experimentación, diversión, aprendizaje y sobre todo, amistad. Todo en torno a la
  cerveza.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://larutadelacebada.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: '/assets/images/logo.png'
twitter_username: estebanz01
github_username:  estebanz01

# Social - for "SEO"
social:
  name: Esteban Zapata
  links:
    - https://twitter.com/estebanz01
    - https://github.com/estebanz01

# Pagination
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Include custom paths
include: ["_pages"]

# Is staticman present
staticman: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      read_time: true
      image: /assets/images/intro1.jpg
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: page
      read_time: false
      image: /assets/images/intro1.jpg
